# Generated by Django 5.2.1 on 2025-07-14 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuKiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.JSONField(blank=True, default=list, help_text='存储数独的统计信息JSON数据')),
                ('solution', models.CharField(blank=True, help_text='81字符的字符串表示完整答案', max_length=81, validators=[django.core.validators.MinLengthValidator(81), django.core.validators.MaxLengthValidator(81)])),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('X', 'Expert')], default='M', max_length=1)),
                ('sloved_nums', models.IntegerField(default=0)),
                ('try_nums', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('mark', models.CharField(editable=False, max_length=32, unique=True)),
            ],
        ),
    ]
