# Generated by Django 5.2.1 on 2025-08-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killerMode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SudokuKiller',
            new_name='KillerSudoku',
        ),
    ]
