# Generated by Django 5.2.3 on 2025-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('bronze', '铜牌'), ('silver', '银牌'), ('gold', '金牌')], default='bronze', max_length=10, verbose_name='成就类型'),
        ),
    ]
