# Generated by Django 5.2.3 on 2025-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_achievement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(default='', verbose_name='成就描述'),
        ),
    ]
