# Generated by Django 5.2.3 on 2025-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('sudoku', '数独'), ('other', '其他')], default='sudoku', max_length=10, verbose_name='成就类型'),
        ),
    ]
