# Generated by Django 5.2.1 on 2025-07-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonMode', '0003_alter_sudoku_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sudoku',
            options={},
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='puzzle',
            field=models.JSONField(blank=True, default=list, help_text='存储数独的统计信息JSON数据'),
        ),
    ]
