# Generated by Django 5.2.1 on 2025-07-14 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonMode', '0004_alter_sudoku_options_alter_sudoku_puzzle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sudoku',
            options={'ordering': ['-created_at'], 'verbose_name': '数独谜题', 'verbose_name_plural': '数独谜题'},
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='puzzle',
            field=models.CharField(help_text='81字符的字符串表示数独题目(0表示空格)', max_length=81, validators=[django.core.validators.MinLengthValidator(81), django.core.validators.MaxLengthValidator(81)]),
        ),
    ]
