# Generated by Django 5.2.1 on 2025-08-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonMode', '0005_alter_sudoku_options_alter_sudoku_puzzle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sudoku',
            new_name='CommonSudoku',
        ),
    ]
