# Generated by Django 5.2.1 on 2025-05-17 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sudoku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puzzle",
                    models.CharField(
                        help_text="81字符的字符串表示数独题目(0表示空格)",
                        max_length=81,
                        validators=[
                            django.core.validators.MinLengthValidator(81),
                            django.core.validators.MaxLengthValidator(81),
                        ],
                    ),
                ),
                (
                    "solution",
                    models.CharField(
                        blank=True,
                        help_text="81字符的字符串表示完整答案",
                        max_length=81,
                        validators=[
                            django.core.validators.MinLengthValidator(81),
                            django.core.validators.MaxLengthValidator(81),
                        ],
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("E", "Easy"),
                            ("M", "Medium"),
                            ("H", "Hard"),
                            ("X", "Expert"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("sloved_nums", models.BooleanField(default=0)),
                ("try_nums", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mark", models.CharField(editable=False, max_length=32, unique=True)),
            ],
            options={
                "verbose_name": "数独谜题",
                "verbose_name_plural": "数独谜题",
                "ordering": ["-created_at"],
            },
        ),
    ]
