# Generated by Django 5.2.1 on 2025-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudoku",
            name="sloved_nums",
            field=models.IntegerField(default=0),
        ),
    ]
