# Generated by Django 4.2.21 on 2025-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudo', '0002_alter_sudoku_sloved_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
